/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosParaEmpleado.Actualizar;

import FormularioParaEmpleado.Model;
import BaseInternalFrame.BaseInterenalFrame;
import presentacion.validacion;
/**
 *
 * @author DIEGO
 */
public class FrmActualizarEmpleado extends BaseInterenalFrame<Interface.presenter> implements Interface.vista{
    private Model model;
    
    public FrmActualizarEmpleado() {
        initComponents();
        model = new Model(nombre, apellidoP,apellidoM,direccion, telefono,dni,
                idSucursal.getSelectedIndex()+1,idCargo.getSelectedIndex()+1,contra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        apellidoM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        idCargo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        idSucursal = new javax.swing.JComboBox<>();
        apellidoP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EDITAR EMPLEADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 27, -1, -1));

        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, 30));

        apellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoMKeyTyped(evt);
            }
        });
        getContentPane().add(apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 163, -1));

        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 84, -1, -1));

        jLabel7.setText("CONTRASEÑA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel4.setText("DIRECCION: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel8.setText("DNI:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, -1, -1));

        jLabel5.setText("TELEFONO: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniKeyTyped(evt);
            }
        });
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 163, -1));

        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionKeyTyped(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 470, 30));

        jLabel9.setText("CARGO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 161, -1));

        jLabel11.setText("SUCURSAL:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 169, -1));

        contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraKeyTyped(evt);
            }
        });
        getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 169, -1));

        idCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAJERO", "ALMACENERO", "AYUDANTE", "ADMINISTRADOR" }));
        getContentPane().add(idCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 171, -1));

        jLabel2.setText("APELLIDO PATERNO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 141, -1, -1));

        idSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARYFE TRUJILLO" }));
        getContentPane().add(idSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 161, 30));

        apellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoPKeyTyped(evt);
            }
        });
        getContentPane().add(apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 163, -1));

        jLabel6.setText("APELLIDO MATERNO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        presentador.actualizar(model);
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        validacion.validarCaracteres(evt, nombre.getText(), 30);
    }//GEN-LAST:event_nombreKeyTyped

    private void dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniKeyTyped
        validacion.validarNumeros(evt, dni.getText(), 8);
    }//GEN-LAST:event_dniKeyTyped

    private void apellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoPKeyTyped
        validacion.validarCaracteres(evt, apellidoP.getText(), 30);
    }//GEN-LAST:event_apellidoPKeyTyped

    private void apellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoMKeyTyped
        validacion.validarCaracteres(evt, apellidoM.getText(), 30);
    }//GEN-LAST:event_apellidoMKeyTyped

    private void direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyTyped
        validacion.tamaño(evt, direccion.getText(), 80);
    }//GEN-LAST:event_direccionKeyTyped

    private void contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraKeyTyped
        validacion.tamaño(evt, contra.getText(), 20);
    }//GEN-LAST:event_contraKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        validacion.validarNumeros(evt, telefono.getText(), 10);
    }//GEN-LAST:event_telefonoKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String idEmpleado = javax.swing.JOptionPane.showInputDialog(this,"ID de Empleado","Consulta Empleado",javax.swing.JOptionPane.QUESTION_MESSAGE);
        model.setIdEmpleado(idEmpleado);
        presentador.buscar(model);
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoM;
    private javax.swing.JTextField apellidoP;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JPasswordField contra;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JComboBox<String> idCargo;
    private javax.swing.JComboBox<String> idSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Interface.presenter crearPresentador() {
        return new Presenter(this);
    }

    @Override
    public void limpiar() {
        this.nombre.setText("");
        this.apellidoP.setText("");
        this.apellidoM.setText("");
        this.direccion.setText("");
        this.telefono.setText("");
        this.dni.setText("");
        this.idSucursal.setSelectedIndex(0);
        this.idCargo.setSelectedIndex(0);
        this.contra.setText("");
    }

    @Override
    public void mostrarResultadosDeBusqueda(String nombre, String apellidoP,String apellidoM,String direccion,
                String telefono,String dni,int idSucursal,int idCargo) {
        
        this.nombre.setText(nombre);
        this.apellidoP.setText(apellidoP);
        this.apellidoM.setText(apellidoM);
        this.direccion.setText(direccion);
        this.telefono.setText(telefono);
        this.dni.setText(dni);
        this.idSucursal.setSelectedIndex(idSucursal-1);
        this.idCargo.setSelectedIndex(idCargo-1);
        this.contra.setText("");
    }
}
